apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: ashwinbittu/php-k8s-app:43-fe3ac41caf074244628bbb0378dfb63ece5431e9
        name: solar-system
        ports: 
        - containerPort: 80
