apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: ashwinbittu/php-k8s-app:26-18f42790177dae6ce74102f2b48718959868abc8
        name: solar-system
        ports: 
        - containerPort: 80
