apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: ashwinbittu/php-k8s-app:25-faefb804431b9cf7a258458874d29028224adcb9
        name: solar-system
        ports: 
        - containerPort: 80
