apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: ashwinbittu/php-k8s-app:42-6cd940c63956650c79cf44dafc9d8c2624492d93
        name: solar-system
        ports: 
        - containerPort: 80
