apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: ashwinbittu/php-k8s-app:46-fad479216522ffab356b7c8bdcff374f3873cb15
        name: solar-system
        ports: 
        - containerPort: 80
